# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:title
relative_permalinks: true

# Setup
title:               The Royal Liar
tagline:             'MMI Highschool Newspaper'
description:         '<img class="rl-logo" src="/images/royalliar.svg" alt="The Royal Liar">'
url:                 http://theroyalliar.github.io
baseurl:             /
paginate:            12
lsi:                 true

# About/contact
author:
  name:              The Liars
  url:               http://theroyalliar.github.io
  email:             rl@marymountrome.com

# Automatic Task
exclude:
  - build.sh
  - .travis.yml
  - vendor

# Monthly Archives
jekyll-archives:
  enabled:
    - month
  layouts:
    month: archive
  permalinks:
    month: '/:year/:month/'

# Category Archives
category_archive:
  layout: category
  slugify: true
  path: 'category'

# Plugins
gems:
  - jekyll-archives
